### ISSUE TITLE
Breaking changes in quarto 1.4

### ISSUE THREAD

**Issue by fradav** [pandoc-ext/diagram#13]
Hi, quarto 1.4 changed the AST handling for figures in 1.4, so the actual `pandoc.Figure` code doesn’t work anymore for this release.

See https://quarto.org/docs/prerelease/1.4/lua_changes.html#support-for-crossreferenceable-elements-in-filters

Should we add a whole "if (quarto.version > 1.4)" code path for this?
I’m still figuring out how to wrap the `pandoc.Figure` correctly now.

**Comment by danmackinlay** [comment]
Relevant information from quarto devs in [this discussion](https://github.com/quarto-dev/quarto-cli/discussions/8926#discussioncomment-8625015)

**Comment by tarleb** [comment]
The filter seems to work fine with Quarto 1.5, so I'm closing this. The only issue is with `filename` attributes, for which I'll add a note to the README.
