### ISSUE TITLE
Issue when running quarto

### ISSUE THREAD

**Issue by justsharan** [pandoc-ext/diagram#17]
I installed diagram with the command (`quarto install extension pandoc-ext/diagram`), added 
```yaml
filters:
  - diagram
```
to one of the files in my book, and added this to the same file (with `{.tikz}` after the backticks):
``` {.tikz}
\begin{tikzpicture}
    \draw (0,0) circle (1in);
\end{tikzpicture}
```
When I try to preview my book, I get this error:
<img width="1264" alt="image" src="https://github.com/pandoc-ext/diagram/assets/53885408/ada3c126-b1da-420d-8fa8-00c39841b861">
Is there any way to fix it? When I looked up the error, I saw a similar issue in the main quarto repository [here](https://github.com/quarto-dev/quarto-cli/issues/6470), but it didn't have a solution.

**Comment by tarleb** [comment]
Sorry for the late reply: I believe that this was fixed in c5ef7ab56292685c82d4a0575b1e48eb2d545f70, which I merged just now. Please reopen if this the problem persists.
