### ISSUE TITLE
additional packages for tikz

### ISSUE THREAD

**Issue by lsignac** [pandoc-ext/diagram#2]
It seems to me that additional packages for tikz are not taken into account.
`sample.md` contains : 

```
   {.tikz caption="This is an image, created by **TikZ i.e. LaTeX**."   additionalPackages="\usepackage{adjustbox}"}
```

but in `diagram.lua`  : 
```
local pkgs = opt['additional-packages'] or ''
```
variable `pkgs` remains empty (`opt['additional-packages']` is `nil`). The package is not added, and compilation fails 
(missing `\trimbox`).

If I add `\usepackage{adjustbox}` directly in `local tikz_template` variable, everything works fine.

I don't understand lua enough to make a PR... :)

**Comment by tarleb** [comment]
That line should probably be `local pkgs = opt['additional-packages'] or opt['additionalPackages'] or ''`; the camelCase version was just not handled. One can also use `additional-packages="..."` for the time being.

**Comment by tarleb** [comment]
You're right, I forgot that I changed this to `opt-additional-packages`. The docs have not been updated yet.

**Comment by lsignac** [comment]
Got it... !
You sample.md file contains : 
```
    ```{.tikz caption="This is an image, created by **TikZ i.e. LaTeX**."
        additional-packages="\usepackage{adjustbox}"}
    ...
```

But it should be : 

```
    ```{.tikz caption="This is an image, created by **TikZ i.e. LaTeX**."
        opt-additional-packages="\usepackage{adjustbox}"}
    ...
```

**Comment by tarleb** [comment]
The real reference files are those named `test/input-*.md` now. I'll remove `sample.md`.

**Comment by lsignac** [comment]
Not sure that `test/input-*.md`  are good for the final user.  The first thing I did when I found your filter was trying to compile a sample file  to check that the filter matched my needs. (It matched). I close the issue. Thank you for your work and you blazingly fast answers
