### ISSUE TITLE
make test-tikz fails

### ISSUE THREAD

**Issue by gerstorfer** [pandoc-ext/diagram#22]
Running `make test-tikz` gives the following error: 

~~~
Lua warning: diagram.lua: attempt to call a nil value
Error running filter diagram.lua:
attempt to call a nil value
stack traceback:
	diagram.lua:485: in function <diagram.lua:445>
	[C]: in ?
	[C]: in method 'walk'
	diagram.lua:531: in function 'Pandoc'
stack traceback:
	diagram.lua:531: in function 'Pandoc'
~~~

**Comment by tarleb** [comment]
It seems that this was the combination of the changes in 73caf6217092c4ad7a5e73a4be5946486da3a83b as well as an issue with pandoc's `warn` function. I've pushed commits to address both of these issues.

**Comment by gerstorfer** [comment]
Thank you very much for the very quick fix 🙏
