### ISSUE TITLE
How to use this without `--embed-resources`?

### ISSUE THREAD

**Issue by gabyx** [pandoc-ext/diagram#26]
I am wondering if this works without the `--embed-resources` flag. I would like the file to be outputted in a specified folder.
Is that currently supported because the image is not visible in the html output only a sha1 hash as the link with `<img src=....>` etc..

**Comment by tarleb** [comment]
Pandoc's `--extract-media` option can be used to that effect, unless I misunderstood the question.

**Comment by gabyx** [comment]
Ah thanks I figured this out, but I understood from the docs that --extract-media would extract all imgs (follow links in source to images) into a folder, but thats not the case, it only extracts the SVG in the mediabag from this extension. I  am confused. So `--extract-media /dir` is essential otherwise there is no data at the constructed link in HTML outputs right?

**Comment by tarleb** [comment]
Wait, now I'm confused, too :sweat_smile: Do you have an example that I could look at?

> So `--extract-media /dir` is essential otherwise there is no data at the constructed link in HTML outputs right?

Yes, that's right.

**Comment by reagle** [comment]
I'm wondering the same.

```
❯ cat test-diagram.md
---
title: "Test: Diagram with mermaid"
date: 2024-08
diagram:
  cache: true
---

# Introduction

This is a test using
[diagram extension](https://github.com/pandoc-ext/diagram)
The
[results](test-mermaid.html)
of [mermaid-filter](https://github.com/raghur/mermaid-filter).
will be different.

``` mermaid
%%| filename: flowchart
%%| fig-cap: A simple flowchart.
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```%
❯ pandoc -s --lua-filter diagram.lua test-diagram.md -o test-diagram.html
```


<img width="666" alt="SCR-20240813-lhho" src="https://github.com/user-attachments/assets/30cba316-6a0e-4042-a1ad-44dc573ee841">

**Comment by tarleb** [comment]
Use `--extract-media` for that. I should probably include this tip prominently in the README.

**Comment by reagle** [comment]
Suggestion: and/or have the filter give a warning.

**Comment by reagle** [comment]
It seems as if `--extract-media` generates random/hash-like names for the media, and these names are different when we switch between png and svg+xml. Perhaps we could raise the issue on pandoc about generating better names that also survive type changes (beyond the change to the extension to the file)?

**Comment by tarleb** [comment]
Image filenames can be set via the `filename` option, e.g.

`````
``` mermaid {filename="flow"}
...
```
`````

or 


`````
``` mermaid
%%| filename=flowchart
...
```
`````

**Comment by reagle** [comment]
Ah, nice. (Perhaps this could be in the README?) And your example speaks to #23 in that both mermaid and Quarto syntax can be used for some specifications...
