### ISSUE TITLE
Mermaid diagrams mangled in docx/odt

### ISSUE THREAD

**Issue by reagle** [pandoc-ext/diagram#27]
````
❯ cat test-diagram.md
---
title: "Test: Diagram with mermaid"
date: 2024-08
diagram:
  cache: true
---

# Introduction

This is a test using
[diagram extension](https://github.com/pandoc-ext/diagram)
The
[results](test-mermaid.html)
of [mermaid-filter](https://github.com/raghur/mermaid-filter).
will be different.

``` mermaid
%%| filename: flowchart
%%| fig-cap: A simple flowchart.
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
❯ pandoc -s --lua-filter diagram.lua test-diagram.md -o test-diagram.docx -w docx
````

<img width="883" alt="SCR-20240813-lihz" src="https://github.com/user-attachments/assets/58526a2d-6ac5-42a0-88ce-8e8b0ca6a230">

**Comment by tarleb** [comment]
That's a bug: the filter produces a SVG image by default, but it seems that ODT does not support SVG images, and pandoc converts the image with an external program. It would be better if the filter would default to PNG images when targetting ODT.

As a temporary workaround, you can configure the mermaid engine to always produce PNG output:

``` yaml
diagram:
  cache: true
  engine:
    mermaid:
      mime-types: [image/png]
```

**Comment by reagle** [comment]
Thanks @tarleb, that does work. (I'll note that mermaid-filter also fails at SVG in docx/odt.)

**Comment by tarleb** [comment]
It seems that the patch didn't fully fix this, thus reopening.

**Comment by tarleb** [comment]
*Now* it's fixed.
