### ISSUE TITLE
Installation script

### ISSUE THREAD

**Issue by giuli635** [pandoc-ext/diagram#33]
Hello, I would like to use this package, but my main worry is that I have to manually manage updates. I don't use quarto, I prefer plain pandoc.
So, I think it could be a great idea to have installation and uninstallation scripts.

**Comment by tarleb** [comment]
Happy to hear. You could give [verstat](https://github.com/tarleb/verstat) a try, but it's still in an early stage.

**Comment by giuli635** [comment]
Oh thank you!
