### ISSUE TITLE
Add cetz support

### ISSUE THREAD

**Issue by benabel** [pandoc-ext/diagram#37]
First, thank you for this awesome package. I would like to know if you have considered adding typst package [cetz](https://typst.app/universe/package/cetz) support, it may be a nice addition to support scientific diagrams.

Typst provides:
- an auto size page `#set page(width: auto, height: auto, margin: .5cm)`
- also pdf, png, svg export

**Comment by tarleb** [comment]
I don't know much about Typst, so I'll need help with this. Is it possible to generate standalone pictures with Typst? 

It would definitely be a nice addition!

**Comment by benabel** [comment]
I can create a pull request and you'll give me some feedbacks to integrate it best on the extension.

**Comment by tarleb** [comment]
That'd be great, thanks!
