### ISSUE TITLE
Usage with Quarto and plantuml diagram

### ISSUE THREAD

**Issue by FabienSe** [pandoc-ext/diagram#6]
I found this information in the readme

> While it is possible to use this filter with Quarto, it is not encouraged. Quarto comes its own system for diagram generation, and that should be used instead.

I looked at the documentation, Quarto comes with native support of Mermaid and Graphviz. This affirmation is then true for those types of diagrams. But I did not see a way to extend the native support with other format like plantuml.

This extension could be a good fit to integrate plantuml support to Quarto ?

Sorry to ping you @cderv, may be you can help to answer my question ?

Thanks a lot for you help!

**Comment by cderv** [comment]
No worry. Feel free to ping me in distant repo like this - otherwise I would miss it. 

And Yes you're right. Quarto supports Mermaid and Graphviz. For Plantuml I believe this is extensions should be safe to use, isn't it @tarleb ?

**Comment by tarleb** [comment]
That's true, it should work, but I didn't test with Quarto yet. I'd actually be grateful if someone could test that and report remaining bugs and incompatibilities, as I hope to do a proper release of this filter soon.

**Comment by tarleb** [comment]
Thank you @FabienSe! Any help is welcome.
